/* مجرى المعرفة — presentation only. Canonical graph/evidence/media stay unchanged. */
(() => {
  'use strict';
  const original = { ...V };
  document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();const app=document.getElementById('app');app.focus();app.scrollIntoView({block:'start'});});
  V.atlas=(q={})=>{if(q.model==='cordoba'&&!q.place)atlasState.place='PLC-CORDOBA';return original.atlas(q);};
  const clampYear = n => Number.isFinite(+n) ? Math.min(1614, Math.max(711, Math.round(+n))) : 960;
  const params = q => new URLSearchParams(q).toString();
  const norm = s => stripDia(s).toLowerCase().replace(/[أإآ]/g,'ا').replace(/ى/g,'ي');
  const date = o => o.type === 'Person' ? (o.born != null || o.died != null ? `${yr(o.born)}–${yr(o.died)}م` : 'السنة المحددة غير معروفة') : o.type === 'Event' ? dual(o.year,o.end,o.hijri) : o.year ? `${o.year}م` : o.type === 'Polity' ? `${yr(o.from)}–${yr(o.to)}م` : '';
  const lead = (title,sub='') => `<header class="page-lead"><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</header>`;
  const empty = (text,link='#/atlas',label='استكشف الأطلس') => `<div class="empty-state"><h2>${esc(text)}</h2><p>غيّر كلمات البحث أو وسّع نطاق الاستكشاف.</p><a class="btn ghost" href="${link}">${esc(label)}</a></div>`;
  const mediaOf = o => MEDIA[o.id] || o.image;
  function image(o,zoom=false,eager=false) {
    const m=mediaOf(o);
    if(!m?.src || !licOK(m.license)) return `<div class="media-unavailable"><span>${TYPE[o.type]?.[0]||'سجل'}</span><p>لا صورة مرخّصة معتمدة لهذا السجل بعد.</p></div>`;
    return `<figure class="knowledge-image" data-media="${esc(o.id)}"><div class="image-stage"><img src="${esc(m.src)}" alt="${esc(m.note||o.name.ar)}" loading="${eager?'eager':'lazy'}" referrerpolicy="no-referrer">${zoom?`<button class="image-zoom" data-zoom-image="${esc(o.id)}">${uiIcon('search')} كبّر الصورة</button>`:''}</div><figcaption><span dir="auto">${esc(m.license)} · ${esc(m.author||'المؤلف غير مذكور')}</span>${m.source?` · <a href="${esc(m.source)}" target="_blank" rel="noopener">المصدر</a>`:''}${m.note?`<p>${esc(m.note)}</p>`:''}</figcaption></figure>`;
  }
  const relatedRows = (id,limit=9) => {
    const grouped=related(id);const items=['Person','Place','Event','Artifact','Document','Work','Polity'].flatMap(t=>(grouped[t]||[]).map(x=>({...x,type:t}))).filter(x=>E[x.id]);
    return items.slice(0,limit).map(x=>`<a class="knowledge-row" href="${href(x.id)}">${typeIcon(x.type)}<span><b>${esc(E[x.id].name.ar)}</b><small>${esc(TYPE[x.type][0])}${!x.rev?` · ${esc(x.rel)}`:''}</small></span>${uiIcon('arrow-left')}</a>`).join('');
  };
  function clock(y,id) {
    return `<div class="knowledge-clock"><div class="clock-heading"><strong id="${id}-y">${y}م <small>${hijri(y)}هـ تقريبًا · ${eraOf(y).name}</small></strong><a href="#/timeline?y=${y}">افتح الزمن</a></div><div class="clock-range"><span>711</span><input id="${id}" type="range" min="711" max="1614" value="${y}" aria-label="السنة" aria-valuetext="${y} ميلادية"><span>1614</span></div><div class="clock-ticks" dir="ltr">${[756,929,1031,1238,1492].map(n=>`<a href="#/?y=${n}" style="inset-inline-start:${(n-711)/903*100}%">${n}</a>`).join('')}</div></div>`;
  }
  function homePanel(id,y) {
    const o=E[id];return `<aside class="explore-context"><div class="context-heading"><span>مكان على الخريطة</span><h1>${esc(o.name.ar)}</h1><div class="context-summary">${(o.summary||[]).slice(0,1).map(([t,c])=>claimSpan(t,c)).join('')||esc(o.kind||'مكان')}</div></div><a class="btn context-action" href="${href(id)}">استكشف ${esc(o.name.ar)} ${uiIcon('arrow-left')}</a>${image(o,false,true)}<div class="context-connections"><h2>متصل بهذا المكان</h2>${relatedRows(id,3)||`<p class="note">لا علاقات منشورة لهذا المكان بعد.</p>`}</div><a class="context-more" href="#/atlas?model=all&place=${encodeURIComponent(id)}&y=${y}&tab=place">المكان في الأطلس</a></aside>`;
  }
  V.home = (q={}) => {
    const y=clampYear(q.y||state.y);state.y=y;
    const selected=E[q.place]?.type==='Place'?q.place:'PLC-CORDOBA';
    const points=new Set([...MAJOR,selected]);
    return `<section class="knowledge-home"><div class="explore-scene">${homePanel(selected,y)}<div class="explore-canvas"><div class="canvas-intro"><h2>ابدأ من مكان</h2><p>اختر موضعًا، ثم اتبع ما يتصل به.</p></div><div class="home-map" id="heroMap" data-place="${selected}">${mapSvg(y,{bbox:[-10,33.2,4,44],focus:selected,only:points,labelIds:new Set(['PLC-CORDOBA','PLC-GRANADA','PLC-TOLEDO','PLC-SEVILLE','PLC-ZARAGOZA','PLC-VALENCIA',selected]),route:id=>`#/?place=${encodeURIComponent(id)}&y=${y}`})}</div><p class="canvas-caption">مواضع حديثة تقريبية؛ لا حدود سياسية تاريخية · Natural Earth (ملك عام)</p></div></div><div class="explore-navigation"><nav aria-label="مداخل الاستكشاف"><a class="active" href="#/atlas?y=${y}">${uiIcon('map-pin')} مكان</a><a href="#/timeline?y=${y}">${uiIcon('flag')} زمن</a><a href="#/people">${uiIcon('user')} شخصية</a><a href="#/timeline?d=glance">${uiIcon('book-open')} حدث</a></nav>${clock(y,'heroY')}</div></section><section class="home-editorial"><div>${lead('طرق أخرى إلى الأندلس','المكان بداية؛ والشاهد يفتح طبقة أخرى من المعرفة.')}<a href="#/stories">اقرأ القصص ${uiIcon('arrow-left')}</a></div><div class="editorial-links"><a href="#/museum"><h2>المجموعة الرقمية</h2><p>آثار ومخطوطات ومصنفات، بصورها وحقوقها.</p></a><a href="#/learn"><h2>تعلّم من الشواهد</h2><p>وحدات قصيرة وأسئلة تربط المعرفة بالدليل.</p></a><a href="#/sources"><h2>كيف نعرف؟</h2><p>المصادر الأولية، والقراءات الحديثة، وحدود ما نعرفه.</p></a></div></section>`;
  };
  const directoryRow = o => `<article class="directory-row"><a href="${href(o.id)}"><span class="row-type">${typeIcon(o.type)}</span><div><h2>${esc(o.name.ar)}</h2><small>${esc((o.roles||[]).join(' · ')||o.kind||TYPE[o.type][0])}</small></div><span class="row-date">${date(o)}</span>${uiIcon('arrow-left')}</a>${(o.summary||[]).length?`<p>${esc(stripCodes(o.summary[0][0]))}</p>`:''}</article>`;
  function directory(type,q={}) {
    const people=type==='Person',s=q.s||'',period=q.period||'';
    const list=Object.values(E).filter(o=>o.type===type).filter(o=>!s||norm(o.name.ar+' '+(o.name.en||'')+' '+(o.roles||[]).join(' ')).includes(norm(s))).filter(o=>!period || (people ? (o.born??o.died)==null?false:Math.floor((o.born??o.died)/100)*100===+period : o.period_group===period)).sort((a,b)=>people?(a.born??a.died??9999)-(b.born??b.died??9999):a.name.ar.localeCompare(b.name.ar,'ar'));
    const choices=people?[...new Set(Object.values(E).filter(o=>o.type==='Person').map(o=>o.born??o.died).filter(n=>n!=null).map(n=>Math.floor(n/100)*100))].sort((a,b)=>a-b).map(n=>[n,`${n}–${n+99}م`]):[...new Set(Object.values(E).filter(o=>o.type==='Place').map(o=>o.period_group).filter(Boolean))].map(k=>[k,geoP(k)]);
    return `<section class="knowledge-directory" data-kind="${type}">${lead(people?'الأشخاص وشبكات المعرفة':'الأماكن وطبقاتها',people?'ابدأ باسم، أو فترة، ثم اكتشف العلاقات والشواهد.':'مدن ومعالم وميادين؛ الموضع باب إلى الزمن والناس.')}<form class="discovery-filter" data-route="${people?'people':'places'}"><label>بحث في ${people?'الأشخاص':'الأماكن'}<input name="s" value="${esc(s)}" placeholder="${people?'اسم أو دور':'اسم المكان'}"></label><label>الفترة<select name="period"><option value="">كل الفترات</option>${choices.map(([n,l])=>`<option value="${esc(n)}" ${String(n)===period?'selected':''}>${esc(l)}</option>`).join('')}</select></label><button class="btn" type="submit">اعرض النتائج</button></form><p class="result-count" role="status">${list.length} ${people?'شخصية':'مكانًا'}${s?` · نتائج «${esc(s)}»`:''}</p><div class="${people?'directory-list':'place-collection'}">${list.map(o=>people?directoryRow(o):`<article class="place-entry">${image(o)}<div><h2><a href="${href(o.id)}">${esc(o.name.ar)}</a></h2><p>${esc(stripCodes(o.summary?.[0]?.[0]||o.kind||''))}</p><a class="text-link" href="${href(o.id)}">استكشف المكان ${uiIcon('arrow-left')}</a></div></article>`).join('')||empty('لا نتائج ضمن هذا الاختيار',people?'#/people':'#/places','اعرض الجميع')}</div></section>`;
  }
  V.people=q=>directory('Person',q);V.places=q=>directory('Place',q);
  V.museum=(q={})=>{
    const kinds=['Artifact','Document','Work','Resource','Language'];const t=kinds.includes(q.t)?q.t:'';
    const all=Object.values(E).filter(o=>kinds.includes(o.type));const groups=(t?[t]:kinds).map(k=>({k,items:all.filter(o=>o.type===k)}));
    return `<section class="digital-collection">${lead('المجموعة الرقمية','قطع ووثائق وكتب؛ لكل أثر سياقه، ولكل صورة مصدرها.')}<nav class="collection-filter" aria-label="نوع المجموعة">${[['','الكل'],...kinds.map(k=>[k,TYPE[k][0]])].map(([k,l])=>`<a href="#/museum${k?'?t='+k:''}" ${t===k?'aria-current="page"':''}>${esc(l)}</a>`).join('')}</nav>${groups.map(({k,items})=>`<section class="collection-section"><div class="section-heading"><h2>${{Artifact:'القطع والآثار',Document:'المخطوطات',Work:'المصنفات',Resource:'الموارد الرقمية',Language:'اللغات'}[k]}</h2><span>${items.length} سجلات</span></div><div class="collection-items">${items.map(o=>`<article class="collection-item">${image(o)}<div><span class="type">${TYPE[k][0]}${o.year?' · '+o.year+'م':''}</span><h3><a href="${href(o.id)}">${esc(o.name.ar)}</a></h3><p>${esc(stripCodes(o.summary?.[0]?.[0]||''))}</p><a class="text-link" href="${href(o.id)}">افتح السجل ${uiIcon('arrow-left')}</a></div></article>`).join('')}</div></section>`).join('')}</section>`;
  };
  V.timeline=(q={})=>{
    const y=clampYear(q.y||state.y),span=['century','decade','year'].includes(q.zoom)?q.zoom:'century';const size={century:100,decade:10,year:1}[span];const lo=Math.floor(y/size)*size,hi=lo+size-1;
    const all=Object.values(E).filter(o=>o.type==='Event').sort((a,b)=>a.year-b.year);const events=q.scope==='all'?all:all.filter(e=>(e.end||e.year)>=lo && e.year<=hi);const era=eraOf(y);
    return `<section class="chronicle">${lead('الزمن: طبقات متصلة','حرّك السنة، ثم اقترب من قرن أو عقد أو حدث.')}<div class="chronicle-control">${clock(y,'timelineYear')}<nav class="density" aria-label="مقياس الزمن">${[['century','قرن'],['decade','عقد'],['year','سنة']].map(([k,l])=>`<a class="chip" href="#/timeline?y=${y}&zoom=${k}" ${span===k?'aria-current="page"':''}>${l}</a>`).join('')}<a class="chip" href="#/timeline?y=${y}&zoom=${span}&scope=all" ${q.scope==='all'?'aria-current="page"':''}>كل الأحداث</a></nav></div><div class="era-context"><h2>${esc(era.name)}</h2><span>${eraSpan(era)}م</span>${(era.summary||[]).map(([t,c])=>`<p>${claimSpan(t,c)}</p>`).join('')||`<p>${esc(era.note||'')}</p>`}</div><h2>${q.scope==='all'?'الأحداث المنشورة':`${lo}–${hi}م`}</h2><div class="chronicle-events">${events.map(e=>`<article class="chronicle-event"><div class="event-year">${dual(e.year,e.end,e.hijri)}</div><div><span>${esc(e.kind||'حدث')}</span><h3><a href="${href(e.id)}">${esc(e.name.ar)}</a></h3><div>${summaryBlock(e)}</div>${E[e.place]?`<a class="text-link" href="${href(e.place)}">${uiIcon('map-pin')} ${esc(E[e.place].name.ar)}</a>`:''}</div></article>`).join('')||empty('لا حدث منشور في هذا النطاق',`#/timeline?y=${y}&scope=all`,'اعرض جميع الأحداث')}</div></section>`;
  };
  const sourceRow=(id,S)=>`<details class="bibliography-record" id="source-${esc(id)}"><summary><span>${S.tier==='أولي'?'مصدر أولي':'مرجع · '+esc(S.tier||'غير مصنف')}</span><h2>${esc(S.title)}</h2>${uiIcon('arrow-left')}</summary><div class="bibliography-detail">${S.author?`<p>${esc(S.author)}</p>`:''}<p>${esc(S.pub||'بيانات الطبعة غير متحققة')}</p><dl><dt>الحقوق</dt><dd>${esc(S.rights||'غير معروف')}${S.rights_note?' — '+esc(S.rights_note):''}</dd>${S.url_checked?`<dt>فحص الرابط</dt><dd>${esc(S.url_checked)}</dd>`:''}</dl>${S.url?`<a class="text-link" href="${esc(S.url)}" target="_blank" rel="noopener">افتح المصدر</a>`:''}</div></details>`;
  V.sources=(q={})=>{
    const s=q.s||'',kind=q.kind||'';const all=Object.entries(SOURCES).filter(([id,S])=>(!s||norm(S.title+' '+(S.author||'')).includes(norm(s)))&&(!kind||(kind==='primary')===(S.tier==='أولي'))).sort((a,b)=>(b[1].tier==='أولي')-(a[1].tier==='أولي')||a[1].title.localeCompare(b[1].title,'ar'));
    return `<section class="bibliography">${lead('المصادر: المعرفة وشواهدها','قيمة المصدر في الاستشهاد مستقلة عن حق إعادة نشره. افتح السجل لبيانات الطبعة والحقوق.')}<form class="discovery-filter" data-route="sources"><label>اسم المصدر أو المؤلف<input name="s" value="${esc(s)}" placeholder="ابحث في المراجع"></label><label>نوع المصدر<select name="kind"><option value="">كل المصادر</option><option value="primary" ${kind==='primary'?'selected':''}>المصادر الأولية</option><option value="reference" ${kind==='reference'?'selected':''}>الدراسات والمراجع</option></select></label><button class="btn">اعرض النتائج</button></form><p class="result-count" role="status">${all.length} مصدرًا</p>${all.map(([id,S])=>sourceRow(id,S)).join('')||empty('لا مصادر تطابق البحث','#/sources','اعرض جميع المصادر')}</section>`;
  };
  V.play=(q={})=>{
    const i=Math.max(0,Math.min(QUIZ.length-1,(+q.n||1)-1));const quiz=QUIZ[i];return `<section class="quiz-session">${lead('اختبر المعرفة، وافتح دليلها','سؤال واحد في كل مرة؛ الإجابة تقود إلى تفسيرها وشاهدها.')}<div class="quiz-progress"><span>السؤال ${i+1} من ${QUIZ.length}</span><progress value="${i+1}" max="${QUIZ.length}"></progress></div>${quizCard(quiz)}<nav class="quiz-navigation" aria-label="التنقل بين الأسئلة">${i>0?`<a class="btn ghost" href="#/play?n=${i}">السابق</a>`:''}<button class="btn ghost" data-retry-quiz>حاول من جديد</button>${i+1<QUIZ.length?`<a class="btn" href="#/play?n=${i+2}">السؤال التالي</a>`:'<a class="btn" href="#/learn">تابع التعلّم</a>'}</nav></section>`;
  };
  V.learn=(q={})=>q.m?original.learn(q):`<section class="learning-path">${lead('تعلّم من الشواهد','اختر وحدة؛ اقرأ خطواتها، ثم اختبر فهمك وافتح الأدلة.')}<div class="learning-list">${learnSorted().map(m=>`<article><div class="learning-meta"><span>${esc(m.level)} · ${m.minutes} دقيقة</span><span>${m.steps.length} خطوات</span></div><div><h2><a href="#/learn?m=${m.id}">${esc(m.title)}</a></h2><p>${esc(plainAr(m.summary))}</p><small>${esc(m.period||'')}</small></div><a class="text-link" href="#/learn?m=${m.id}">ابدأ الوحدة ${uiIcon('arrow-left')}</a></article>`).join('')}</div></section>`;
  V.stories=(q={})=>q.s?original.stories(q):`<section class="story-index">${lead('قصص تتصل بالمكان','سرد على محطات، يتزامن مع الخريطة، ويكشف شاهد كل معلومة.')}<div class="story-list">${STORIES.map(st=>`<article><div><span>${esc(st.period||'')}</span><h2><a href="#/stories?s=${st.id}">${esc(st.title)}</a></h2><p>${esc(st.summary||'')}</p><div class="story-links"><a class="btn" href="#/stories?s=${st.id}">اقرأ القصة</a><a class="text-link" href="#/atlas?model=all&story=${st.id}&step=1&tab=sto">على الأطلس</a></div>${st.warning?`<p class="note">${esc(st.warning)}</p>`:''}</div><ol>${st.steps.map(step=>`<li>${esc(step.title)}</li>`).join('')}</ol></article>`).join('')}</div></section>`;
  V.entity=id=>{
    const o=E[id];if(!o || ['Event','Polity'].includes(o.type))return original.entity(id);
    const isPerson=o.type==='Person',isPlace=o.type==='Place',isCollection=!isPerson&&!isPlace;
    const rel=related(id),places=(rel.Place||[]).map(x=>E[x.id]).filter(o=>typeof o?.lat==='number');
    const fields=[];if(o.name.en)fields.push(['النقحرة',`<bdi>${esc(o.name.en)}</bdi>`]);if(o.roles?.length)fields.push(['المجال',esc(o.roles.join(' · '))]);if(date(o))fields.push(['الزمن',date(o)]);
    if(o.name.parts)Object.entries(o.name.parts).forEach(([k,v])=>fields.push([({ism:'الاسم',kunya:'الكنية',nasab:'النسب',nisba:'النسبة',laqab:'اللقب'})[k]||k,esc(v)]));
    if(o.name.variants?.length)fields.push(['الأسماء',esc(o.name.variants.join(' · '))]);if(o.holding){fields.push(['مكان الحفظ',esc(o.holding.institution||'غير معروف')],['حقوق سجل القطعة',esc(o.holding.license||'غير معروف')]);}if(o.author&&!E[o.author])fields.push(['المؤلف',esc(o.author)]);
    const events=isPlace?Object.values(E).filter(e=>e.type==='Event'&&e.place===id).sort((a,b)=>a.year-b.year):[];
    const used=[...new Set((o.summary||[]).flatMap(([,c])=>(CLAIMS[c]?.sources||[]).map(s=>s.src)))].filter(s=>SOURCES[s]);
    const map=isPlace?`<div class="entity-map">${mapSvg(state.y,{focus:id,only:new Set([...MAJOR,id])})}<p class="note">${esc(geoQ(o.spatial_quality))} · ${esc(geoA(o.anchor_type))}؛ الموضع تقريبي.</p><a class="text-link" href="#/atlas?model=all&place=${encodeURIComponent(id)}&y=${state.y}&tab=place">افتح في الأطلس</a></div>`:places.length?`<div class="entity-map">${mapSvg(state.y,{only:new Set(places.map(p=>p.id)),focus:places[0].id})}<div class="chips">${places.map(p=>chip(p.id)).join('')}</div><p class="note">العلاقات المنشورة بالمكان؛ ليست مسار سفر مقيسًا.</p></div>`:'';
    return `<section class="historical-profile" data-kind="${o.type}">${crumb(o)}<header class="profile-heading"><span>${TYPE[o.type][0]}</span><h1>${esc(o.name.ar)}</h1>${isPlace?ribbon(state.y):''}</header><div class="profile-grid"><div class="profile-text"><dl class="profile-facts">${fields.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>${summaryBlock(o)}${o.place_note?`<p class="note">${esc(o.place_note)}</p>`:''}${audienceBox(o)}${events.length?`<section class="place-chronicle"><h2>زمن هذا المكان</h2>${events.map(e=>`<a href="${href(e.id)}"><time>${e.year}م</time><span>${esc(e.name.ar)}</span></a>`).join('')}</section>`:''}</div><aside class="profile-context">${image(o,true,true)}${map}</aside></div><section class="profile-relations"><h2>العلاقات المنشورة</h2><div>${relatedRows(id,999)||'<p class="note">لا علاقات منشورة لهذا السجل بعد.</p>'}</div></section><section class="profile-sources"><h2>مصادر هذه الصفحة</h2>${used.map(s=>sourceRow(s,SOURCES[s])).join('')||'<p class="note">لا مصادر مسندة إلى ملخص هذا السجل بعد؛ مصدر الصورة ورخصتها يظهران مع الصورة.</p>'}</section><p class="note">بيانات الإصدار ${esc(RELEASE.release_date||'')} · <a href="#/about">المنهجية والتصحيح</a></p></section>`;
  };
  function enhanceAtlas(q) {
    const root=document.querySelector('#app[data-view="atlas"]>section');if(!root)return;
    root.classList.add('discovery-atlas');root.querySelector('.lyr input[data-lyr="zones"]')?.closest('label')?.remove();
    const main=root.querySelector('.atlas>div');const map=main?.querySelector('#atlasMap');if(!map)return;
    const previous=[...main.children].slice(0,[...main.children].indexOf(map));const details=document.createElement('details');details.className='atlas-options';details.innerHTML='<summary>الفترات والطبقات والأحداث</summary>';previous.forEach(n=>details.append(n));main.prepend(details);main.prepend(map);
    const selected=E[atlasState.place];if(selected){const label=document.createElement('p');label.className='atlas-selected';label.textContent=`المحدد: ${selected.name.ar} · ${atlasState.y}م`;main.insertBefore(label,map);}
    const tabs=root.querySelector('.tabs');if(tabs){tabs.removeAttribute('role');tabs.setAttribute('aria-label','سياق الأطلس');tabs.querySelectorAll('button').forEach(b=>{b.removeAttribute('role');b.setAttribute('aria-pressed',String(b.getAttribute('aria-selected')==='true'));b.removeAttribute('aria-selected');});}
    if(q.model && !q.place && q.model==='cordoba')atlasState.place='PLC-CORDOBA';
    const persist=()=>{try{sessionStorage.setItem('and-exploration',JSON.stringify({model:atlasState.model,y:atlasState.y,place:atlasState.place,tab:atlasState.tab,layers:[...atlasState.layers]}));}catch(_){}};persist();
  }
  function enhance() {
    document.getElementById('app').dataset.design='knowledge-flow';
    const q=Object.fromEntries(new URLSearchParams((location.hash.split('?')[1]||'')));
    document.querySelectorAll('.discovery-filter').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(f));location.hash=`#/${f.dataset.route}?${params(data)}`;}));
    document.querySelectorAll('.knowledge-image img').forEach(img=>{const fail=()=>{if(!img.isConnected)return;const stage=img.parentElement;stage.classList.add('image-failed');const label=document.createElement('p');label.textContent='تعذّر تحميل الصورة. يمكنك فتح المصدر أدناه.';stage.replaceChildren(label);};img.addEventListener('load',()=>{img.dataset.ready='true';},{once:true});img.addEventListener('error',fail,{once:true});if(img.complete&&img.naturalWidth)img.dataset.ready='true';else if(img.complete&&!img.naturalWidth)fail();});
    document.querySelectorAll('[data-zoom-image]').forEach(b=>b.addEventListener('click',()=>openViewer(b.dataset.zoomImage)));
    document.querySelectorAll('input[type="range"]').forEach(r=>r.addEventListener('input',()=>r.setAttribute('aria-valuetext',r.value+' ميلادية')));
    const timeline=document.getElementById('timelineYear');if(timeline)timeline.addEventListener('input',()=>{document.getElementById('timelineYear-y').innerHTML=`${timeline.value}م <small>${hijri(+timeline.value)}هـ تقريبًا · ${eraOf(+timeline.value).name}</small>`;});if(timeline)timeline.addEventListener('change',()=>{state.y=clampYear(timeline.value);location.hash=`#/timeline?y=${state.y}&zoom=${q.zoom||'century'}`;});
    const home=document.getElementById('heroY');if(home)home.addEventListener('change',()=>{location.hash=`#/?place=${encodeURIComponent(document.getElementById('heroMap').dataset.place)}&y=${clampYear(home.value)}`;});
    document.querySelectorAll('[data-retry-quiz]').forEach(b=>b.onclick=()=>route());
    document.querySelectorAll('.quiz .note').forEach(n=>n.setAttribute('role','status'));
    const lesson=document.querySelector('#app[data-view="learn"]');if(lesson&&q.m){lesson.classList.add('lesson-view');const goals=lesson.querySelector('.panel');if(goals){const d=document.createElement('details');d.className='lesson-goals';d.innerHTML='<summary>أهداف الوحدة</summary>';goals.before(d);d.append(goals);}lesson.querySelectorAll('.stepper a').forEach(a=>{a.removeAttribute('role');a.removeAttribute('aria-selected');a.setAttribute('aria-label',a.title);});const list=lesson.querySelector('.stepper');if(list){list.removeAttribute('role');list.setAttribute('aria-label','خطوات الوحدة');}}
    enhanceAtlas(q);
    if(document.querySelector('#app[data-view="map"]')){const era=document.querySelector('#app .eras'),legend=document.querySelector('#app .eralegend');if(era&&legend){const d=document.createElement('details');d.className='map-periods';d.innerHTML='<summary>الفترات التاريخية ومفتاح الزمن</summary>';era.before(d);d.append(era,legend);}}
    document.querySelectorAll('#nav a').forEach(a=>a.classList.contains('on')?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current'));
    document.querySelectorAll('.claim .b[data-c]').forEach(b=>{const c=CLAIMS[b.dataset.c];b.setAttribute('aria-label',`افتح شواهد المعلومة: ${c?.text||'كيف نعرف هذا؟'}`);});
  }
  const viewer=document.createElement('dialog');viewer.id='imageViewer';viewer.setAttribute('aria-label','عارض الصورة ومصدرها');document.body.append(viewer);
  let viewerOrigin;
  function openViewer(id){const o=E[id],m=mediaOf(o);if(!m?.src)return;viewerOrigin=document.activeElement;viewer.innerHTML=`<header><h2>${esc(o.name.ar)}</h2><button class="btn ghost" data-close-viewer>إغلاق</button></header><div class="viewer-controls"><button data-image-scale="out">تصغير</button><button data-image-scale="reset">الحجم الأصلي</button><button data-image-scale="in">تكبير</button></div><div class="viewer-image">${image(o,false,true)}</div>`;viewer.showModal();let scale=1;const img=viewer.querySelector('img');viewer.querySelector('[data-close-viewer]').onclick=()=>viewer.close();viewer.querySelectorAll('[data-image-scale]').forEach(b=>b.onclick=()=>{scale=b.dataset.imageScale==='reset'?1:Math.min(4,Math.max(.5,scale+(b.dataset.imageScale==='in'?.5:-.5)));img.style.width=scale*100+'%';img.style.maxWidth='none';});}
  viewer.addEventListener('close',()=>viewerOrigin?.focus());
  function searchKnowledge(s) {
    s=s.trim();const res=document.getElementById('res');const numeric=s.replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c));
    if(/^\d{3,4}$/.test(numeric)){const y=+numeric;res.innerHTML=y>=711&&y<=1614?`<div class="reshdr">ابدأ من سنة ${y}م</div><a href="#/map?y=${y}">${uiIcon('map')}الخريطة الزمنية<small>${eraOf(y).name}</small></a><a href="#/timeline?y=${y}">${uiIcon('flag')}الأحداث والشواهد<small>الزمن</small></a>`:'<div class="search-empty"><b>السنة خارج نطاق هذا الأطلس</b><p>اختر سنة بين 711 و1614م.</p></div>';selReset();return;}
    if(!s){res.innerHTML='<div class="reshdr">ابدأ من اسم أو سنة أو مصدر</div>'+recents().slice(0,4).map(id=>resRow(E[id],'زُرت مؤخرًا')).join('')+['PLC-CORDOBA','PER-016','EVT-003'].filter(id=>E[id]&&!recents().includes(id)).map(id=>resRow(E[id])).join('');selReset();return;}
    const hits=Object.values(E).filter(o=>norm([o.name.ar,o.name.en,o.name.es,...(o.name.variants||[])].filter(Boolean).join(' ')).includes(norm(s))).slice(0,36);const src=Object.entries(SOURCES).filter(([id,S])=>norm(S.title+' '+(S.author||'')).includes(norm(s))).slice(0,6);
    const order=['Place','Person','Event','Polity','Artifact','Document','Work','Language','Resource'];res.innerHTML=order.map(t=>{const l=hits.filter(o=>o.type===t);return l.length?`<div class="reshdr">${TYPE[t][0]} · ${l.length}</div>${l.map(o=>resRow(o)).join('')}`:'';}).join('')+(src.length?`<div class="reshdr">المصادر · ${src.length}</div>${src.map(([id,S])=>`<a href="#/sources?s=${encodeURIComponent(S.title)}">${uiIcon('book-open')}${esc(S.title)}<small>${S.tier==='أولي'?'مصدر أولي':'مرجع'}</small></a>`).join('')}`:'')||'<div class="search-empty"><h2>لم نعثر على نتائج</h2><p>جرّب اسمًا آخر أو سنة، أو افتح الأطلس.</p><a href="#/atlas">استكشف الأطلس</a></div>';selReset();
  }
  search=searchKnowledge;
  const cmd=document.getElementById('cmd'),prov=document.getElementById('prov');
  [cmd,prov].forEach(el=>{el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.setAttribute('aria-label',el===cmd?'البحث في منصة الأندلس':'شواهد المعلومة');});
  document.getElementById('q').setAttribute('aria-label','اسم أو سنة أو مصدر');
  cmd.querySelector('.box').insertAdjacentHTML('afterbegin','<div class="search-heading"><h2>ابحث في المعرفة</h2><button type="button" class="btn ghost" id="closeSearch">إغلاق</button></div>');
  document.getElementById('closeSearch').onclick=()=>cmd.classList.remove('on');
  let activeModal=null,modalOrigin=null;
  function syncModal(){const next=cmd.classList.contains('on')?cmd:prov.classList.contains('open')?prov:null;cmd.inert=next!==cmd;prov.inert=next!==prov;cmd.setAttribute('aria-hidden',String(next!==cmd));prov.setAttribute('aria-hidden',String(next!==prov));if(next===activeModal)return;if(next){if(!activeModal)modalOrigin=next===cmd?document.getElementById('kbtn'):document.activeElement;document.querySelector('.wrap').inert=true;document.body.classList.add('modal-open');activeModal=next;(next===cmd?document.getElementById('q'):next.querySelector('button'))?.focus();}else{document.querySelector('.wrap').inert=false;document.body.classList.remove('modal-open');activeModal=null;modalOrigin?.focus();}}
  [cmd,prov].forEach(el=>new MutationObserver(syncModal).observe(el,{attributes:true,attributeFilter:['class']}));
  syncModal();
  document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!activeModal)return;const items=[...activeModal.querySelectorAll('a[href],button:not([disabled]),input,[tabindex="0"]')].filter(el=>el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}});
  V.design=()=>`<section class="design-language">${lead('مجرى المعرفة','المكان والزمن والعلاقة والشاهد: أربعة عناصر تبني لغة المنصة.')}<h2>هوية واحدة، ثلاثة أوضاع</h2><p>الفاتح للاستكشاف، المخطوط للقراءة الوثائقية، والليل لتباين مريح. وظائف اللون ثابتة عبر الأوضاع.</p><h2>المكونات</h2><div class="knowledge-spec"><p>خريطة معرفة ومحور زمن ولوحة سياق.</p><p>ملف تاريخي، فهرس أشخاص، سجل مصدر، وعارض صورة.</p><p>الشاهد قريب من المعلومة، والحقوق ملازمة للصورة.</p></div><h2>أزرار واختيارات</h2><div class="design-controls"><a class="btn" href="#/atlas">استكشف الأطلس</a><a class="btn ghost" href="#/sources">المصادر</a><button disabled>غير متاح</button><button aria-busy="true" disabled>جارٍ التحميل…</button></div><h2>حالات المعرفة</h2><p>${Object.entries(STATUS).filter(([k])=>['fact','partial','inference'].includes(k)).map(([k,[n]])=>`<span class="status-example"><i class="b ${k}"></i>${n}</span>`).join('')}</p><h2>نظام القراءة</h2><p>واجهة عربية من اليمين إلى اليسار، وخريطة ومحور زمن باتجاه قياسي للقياس. المتن 16 بكسل، والبيانات 14؛ طول السطر محدد للقراءة الطويلة.</p></section>`;
  window.AndalusUI={enhance};
  try{const saved=JSON.parse(sessionStorage.getItem('and-exploration')||'null');if(saved&&MODEL_META[saved.model]){Object.assign(atlasState,{model:saved.model,y:clampYear(saved.y),place:E[saved.place]?saved.place:null,tab:saved.tab});atlasState.layers=new Set((saved.layers||[]).filter(k=>k==='zones'||ATLAS.layers.some(l=>l.layer_id===k)));}}catch(_){}
  route();
})();
